# .github/workflows/daily-update.yml
name: Load Games

on:
  schedule:
    - cron: '*/20 9-23,0-1 * * *'
      timezone: 'America/Los_Angeles'
jobs:
  load-games:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Load Games API
        run: |
          date=$(TZ='America/Los_Angeles' date '+%Y-%m-%d')
          curl -X GET \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
            -f \
            "https://nbaplayoffgame.com/api/cron/load-games?date=$date"